"""
discover_vault.py — Vault Setup and Config Generation

Purpose: One-time setup script. Confirms vault location, introspects structure,
         reads tagging methodology note, generates config.py and .env.

Usage: python discover_vault.py

Dependencies: python-dotenv, rich, PyYAML
"""

from pathlib import Path
import sys
from rich.console import Console
from rich.table import Table
from rich.prompt import Prompt, Confirm

console = Console()

INBOX_PATTERNS = {"inbox", "capture", "queue"}
DAILY_PATTERNS = {"daily", "journal", "calendar", "daily notes"}
MOCS_PATTERNS = {"mocs", "maps", "index"}
OUTPUT_PATTERNS = {"output", "publish", "production", "export"}


def categorize_folder(name: str) -> str | None:
    """Return the semantic role of a folder name, or None if unknown."""
    lower = name.lower().lstrip("_0123456789 ")
    if lower in INBOX_PATTERNS or any(p in lower for p in INBOX_PATTERNS):
        return "inbox"
    if lower in DAILY_PATTERNS or any(p in lower for p in DAILY_PATTERNS):
        return "daily"
    if lower in MOCS_PATTERNS or any(p in lower for p in MOCS_PATTERNS):
        return "mocs"
    if lower in OUTPUT_PATTERNS or any(p in lower for p in OUTPUT_PATTERNS):
        return "output"
    return None


def find_tagging_note(vault_path: Path) -> Path | None:
    """Search vault recursively for a note with 'tag' in the filename."""
    for md in vault_path.rglob("*.md"):
        if "tag" in md.stem.lower():
            return md
    return None


def detect_tag_format_from_text(text: str) -> str | None:
    """Detect tag format from a single note's text. Returns 'list', 'inline', or None if no tags found."""
    if not text.startswith("---"):
        return None
    end = text.find("---", 3)
    if end == -1:
        return None
    fm_text = text[3:end]
    if "tags:" not in fm_text:
        return None
    for line in fm_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("tags:"):
            return "inline" if "[" in stripped else "list"
    return None


def sample_tag_format(vault_path: Path, sample_count: int = 10) -> str:
    """Sample up to sample_count notes to detect tag format: 'list' or 'inline'."""
    list_count = 0
    inline_count = 0
    checked = 0
    for md in vault_path.rglob("*.md"):
        if checked >= sample_count:
            break
        text = md.read_text(encoding="utf-8", errors="ignore")
        fmt = detect_tag_format_from_text(text)
        if fmt == "inline":
            inline_count += 1
            checked += 1
        elif fmt == "list":
            list_count += 1
            checked += 1
    return "inline" if inline_count > list_count else "list"


def generate_env_content(
    vault_path: Path,
    inbox_path: Path,
    daily_path: Path | None,
    mocs_path: Path | None,
    output_path: Path | None,
    tagging_note_path: Path | None,
    api_key: str,
    tag_format: str,
    date_format: str,
    frontmatter_fields: list[str],
) -> str:
    """Generate .env file content from discovered configuration."""
    lines = [
        f"VAULT_PATH={vault_path}",
        f"INBOX_PATH={inbox_path}",
        f"DAILY_PATH={daily_path or ''}",
        f"MOCS_PATH={mocs_path or ''}",
        f"OUTPUT_PATH={output_path or ''}",
        f"TAGGING_NOTE_PATH={tagging_note_path or ''}",
        f"ANTHROPIC_API_KEY={api_key}",
        f"TAG_FORMAT={tag_format}",
        f"DATE_FORMAT={date_format}",
        f"FRONTMATTER_FIELDS={','.join(frontmatter_fields)}",
        "CLAUDE_MODEL_HEAVY=claude-opus-4-6",
        "CLAUDE_MODEL_LIGHT=claude-haiku-4-5-20251001",
        "CLAUDE_MAX_TOKENS=4096",
    ]
    return "\n".join(lines) + "\n"


CONFIG_PY_TEMPLATE = '''# config.py — auto-generated by discover_vault.py, do not edit manually
# Edit .env for API keys; re-run discover_vault.py to update paths

from pathlib import Path
from dotenv import load_dotenv
import os

_PROJECT_ROOT = Path(__file__).parent.parent
load_dotenv(_PROJECT_ROOT / ".env")

# Vault paths — populated by discover_vault.py
VAULT_PATH = Path(os.environ["VAULT_PATH"])
INBOX_PATH = Path(os.environ["INBOX_PATH"])
DAILY_PATH = Path(os.environ.get("DAILY_PATH", "")) if os.environ.get("DAILY_PATH") else None
MOCS_PATH = Path(os.environ.get("MOCS_PATH", "")) if os.environ.get("MOCS_PATH") else None
OUTPUT_PATH = Path(os.environ.get("OUTPUT_PATH", "")) if os.environ.get("OUTPUT_PATH") else None
TAGGING_NOTE_PATH = Path(os.environ["TAGGING_NOTE_PATH"]) if os.environ.get("TAGGING_NOTE_PATH") else None

# Detected frontmatter conventions
DATE_FORMAT = os.environ.get("DATE_FORMAT", "%Y-%m-%d")
TAG_FORMAT = os.environ.get("TAG_FORMAT", "list")  # "list" or "inline"
FRONTMATTER_FIELDS = os.environ.get("FRONTMATTER_FIELDS", "title,source,tags,created").split(",")

# API
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
CLAUDE_MODEL_HEAVY = os.environ.get("CLAUDE_MODEL_HEAVY", "claude-opus-4-6")
CLAUDE_MODEL_LIGHT = os.environ.get("CLAUDE_MODEL_LIGHT", "claude-haiku-4-5-20251001")
CLAUDE_MAX_TOKENS = int(os.environ.get("CLAUDE_MAX_TOKENS", "4096"))

# Jina
JINA_BASE_URL = "https://r.jina.ai"

# Scripts
SCRIPTS_PATH = Path(__file__).parent
PROJECT_ROOT = SCRIPTS_PATH.parent
PROMPTS_PATH = SCRIPTS_PATH / "prompts"
'''


def main():
    console.rule("[bold blue]Vault Setup — discover_vault.py")

    # Step 1: Confirm vault path
    user_home = Path.home()
    # Vault is in OneDrive/Documents, not Documents directly
    onedrive_docs = user_home / "OneDrive" / "Documents"
    docs_path = onedrive_docs if onedrive_docs.exists() else user_home / "Documents"
    default_vault = "Tim's Vault"
    vault_name = Prompt.ask(
        "Vault folder name inside %USERPROFILE%\\OneDrive\\Documents",
        default=default_vault,
    )
    vault_path = docs_path / vault_name

    if not vault_path.exists():
        console.print(f"[red]Error: {vault_path} does not exist.[/red]")
        sys.exit(1)
    if not (vault_path / ".obsidian").exists():
        console.print(f"[red]Error: {vault_path} does not appear to be an Obsidian vault (.obsidian not found).[/red]")
        sys.exit(1)
    console.print(f"[green]Vault found:[/green] {vault_path}")

    # Step 2: Introspect top-level folders
    top_folders = [f for f in vault_path.iterdir() if f.is_dir() and not f.name.startswith(".")]
    roles = {}
    for folder in top_folders:
        role = categorize_folder(folder.name)
        if role:
            roles[role] = folder

    console.print("\n[bold]Detected folder roles:[/bold]")
    for role in ["inbox", "daily", "mocs", "output"]:
        detected = roles.get(role)
        console.print(f"  {role}: {detected.name if detected else '[not detected]'}")

    # Allow overrides
    for role in ["inbox", "daily", "mocs", "output"]:
        current = roles.get(role)
        prompt_msg = f"Folder for '{role}' (leave blank to skip)"
        default_val = current.name if current else ""
        user_input = Prompt.ask(prompt_msg, default=default_val)
        if user_input:
            candidate = vault_path / user_input
            if candidate.exists():
                roles[role] = candidate
            else:
                if Confirm.ask(f"Create {candidate}?"):
                    candidate.mkdir(parents=True)
                    roles[role] = candidate

    if "inbox" not in roles:
        console.print("[red]Inbox folder is required. Aborting.[/red]")
        sys.exit(1)

    # Step 3: Tagging note
    tagging_note = find_tagging_note(vault_path)
    if tagging_note:
        console.print(f"\n[green]Found tagging note:[/green] {tagging_note}")
        tag_content = tagging_note.read_text(encoding="utf-8", errors="ignore")
        tag_format = detect_tag_format_from_text(tag_content) or sample_tag_format(vault_path)
        console.print(f"  Detected tag format: {tag_format}")
    else:
        console.print("\n[yellow]No tagging note found. Sampling vault to detect format...[/yellow]")
        tag_format = sample_tag_format(vault_path)
        console.print(f"  Detected tag format: {tag_format}")

    # Step 4: API key
    api_key = Prompt.ask("\nAnthropic API key", password=True)

    # Step 5: Write .env
    env_content = generate_env_content(
        vault_path=vault_path,
        inbox_path=roles["inbox"],
        daily_path=roles.get("daily"),
        mocs_path=roles.get("mocs"),
        output_path=roles.get("output"),
        tagging_note_path=tagging_note,
        api_key=api_key,
        tag_format=tag_format,
        date_format="%Y-%m-%d",
        frontmatter_fields=["title", "source", "tags", "created"],
    )
    env_path = Path(__file__).parent.parent / ".env"
    env_path.write_text(env_content, encoding="utf-8", newline="\n")
    console.print(f"\n[green]Written:[/green] {env_path}")

    # Step 6: Write config.py
    config_path = Path(__file__).parent / "config.py"
    config_path.write_text(CONFIG_PY_TEMPLATE, encoding="utf-8", newline="\n")
    console.print(f"[green]Written:[/green] {config_path}")

    # Step 7: Summary table
    table = Table(title="Configuration Summary")
    table.add_column("Key", style="cyan")
    table.add_column("Value", style="white")
    table.add_row("Vault path", str(vault_path))
    table.add_row("Inbox", str(roles["inbox"]))
    table.add_row("Daily notes", str(roles.get("daily", "not set")))
    table.add_row("MOCs", str(roles.get("mocs", "not set")))
    table.add_row("Output", str(roles.get("output", "not set")))
    table.add_row("Tagging note", str(tagging_note or "not found"))
    table.add_row("Tag format", tag_format)
    table.add_row("API key", "***" + api_key[-4:] if api_key else "not set")
    console.print(table)
    console.print("\n[yellow]Reminder: add .env to .gitignore if using version control.[/yellow]")


if __name__ == "__main__":
    main()
